export const storeCategories = [
  {
    id: 'footwear',
    title: 'Footwear',
    deck: 'Sculptural shoes, altered soles, wearable objects.',
    visualTone: 'ink',
  },
  {
    id: 'bags',
    title: 'Bags',
    deck: 'Body-carried forms, hardware, modular containers.',
    visualTone: 'steel',
  },
  {
    id: 'jewelry',
    title: 'Jewelry',
    deck: 'Small body extensions, talismans, metal and skin studies.',
    visualTone: 'bone',
  },
  {
    id: 'accessories',
    title: 'Accessories',
    deck: 'Belts, attachments, masks, fragments and utility pieces.',
    visualTone: 'skin',
  },
  {
    id: 'archive',
    title: 'Archive',
    deck: 'Collections, studies, prototypes and special projects.',
    visualTone: 'void',
  },
];

export const storeProducts = [
  {
    id: 'bone-platform-01',
    name: 'Bone Platform 01',
    category: 'footwear',
    price: 1480,
    currency: 'USD',
    available: true,
    featured: 1,
    bestSelling: 5,
    date: '2026-02-12',
    tags: ['2026', 'bone', 'prototype'],
    visualTone: 'bone',
  },
  {
    id: 'black-sole-study',
    name: 'Black Sole Study',
    category: 'footwear',
    price: 920,
    currency: 'USD',
    available: false,
    featured: 5,
    bestSelling: 4,
    date: '2025-11-18',
    tags: ['2025', 'black', 'prototype-sale'],
    visualTone: 'ink',
  },
  {
    id: 'silver-toe-object',
    name: 'Silver Toe Object',
    category: 'footwear',
    price: 1320,
    currency: 'USD',
    available: true,
    featured: 2,
    bestSelling: 3,
    date: '2026-01-28',
    tags: ['2026', 'silver'],
    visualTone: 'steel',
  },
  {
    id: 'skin-carrier',
    name: 'Skin Carrier',
    category: 'bags',
    price: 1180,
    currency: 'USD',
    available: true,
    featured: 1,
    bestSelling: 2,
    date: '2026-03-03',
    tags: ['2026', 'skin'],
    visualTone: 'skin',
  },
  {
    id: 'hardware-sling',
    name: 'Hardware Sling',
    category: 'bags',
    price: 980,
    currency: 'USD',
    available: true,
    featured: 3,
    bestSelling: 1,
    date: '2025-09-14',
    tags: ['2025', 'black', 'silver'],
    visualTone: 'black-steel',
  },
  {
    id: 'archive-pouch',
    name: 'Archive Pouch',
    category: 'bags',
    price: 460,
    currency: 'USD',
    available: false,
    featured: 6,
    bestSelling: 8,
    date: '2024-04-21',
    tags: ['2024', 'archive', 'black'],
    visualTone: 'void',
  },
  {
    id: 'spine-ring',
    name: 'Spine Ring',
    category: 'jewelry',
    price: 340,
    currency: 'USD',
    available: true,
    featured: 1,
    bestSelling: 3,
    date: '2026-03-18',
    tags: ['2026', 'silver'],
    visualTone: 'steel',
  },
  {
    id: 'bone-chain',
    name: 'Bone Chain',
    category: 'jewelry',
    price: 620,
    currency: 'USD',
    available: true,
    featured: 2,
    bestSelling: 2,
    date: '2025-12-02',
    tags: ['2025', 'bone'],
    visualTone: 'bone',
  },
  {
    id: 'skin-ear-piece',
    name: 'Skin Ear Piece',
    category: 'jewelry',
    price: 280,
    currency: 'USD',
    available: false,
    featured: 7,
    bestSelling: 7,
    date: '2024-10-09',
    tags: ['2024', 'skin', 'archive'],
    visualTone: 'skin',
  },
  {
    id: 'black-harness-fragment',
    name: 'Black Harness Fragment',
    category: 'accessories',
    price: 740,
    currency: 'USD',
    available: true,
    featured: 1,
    bestSelling: 1,
    date: '2026-02-24',
    tags: ['2026', 'black'],
    visualTone: 'ink',
  },
  {
    id: 'silver-belt-object',
    name: 'Silver Belt Object',
    category: 'accessories',
    price: 860,
    currency: 'USD',
    available: true,
    featured: 4,
    bestSelling: 5,
    date: '2025-07-30',
    tags: ['2025', 'silver'],
    visualTone: 'steel',
  },
  {
    id: 'prototype-mask',
    name: 'Prototype Mask',
    category: 'accessories',
    price: 510,
    currency: 'USD',
    available: false,
    featured: 8,
    bestSelling: 6,
    date: '2024-12-19',
    tags: ['2024', 'prototype', 'prototype-sale'],
    visualTone: 'void',
  },
];

export const archiveCollections = [
  {
    group: 'Current / Recent Collections',
    items: [
      { title: '2026 Collection', href: '#/store/archive?tag=2026' },
      { title: '2025 Collection', href: '#/store/archive?tag=2025' },
      { title: '2024 Collection', href: '#/store/archive?tag=2024' },
    ],
  },
  {
    group: 'Color / Material Drops',
    items: [
      { title: 'Black', href: '#/store/archive?tag=black' },
      { title: 'Silver', href: '#/store/archive?tag=silver' },
      { title: 'Bone', href: '#/store/archive?tag=bone' },
      { title: 'Skin', href: '#/store/archive?tag=skin' },
    ],
  },
  {
    group: 'Collaborations / Special Projects',
    items: [
      { title: 'Prototype Sale', href: '#/store/archive?tag=prototype-sale' },
      { title: 'Special Objects', href: '#/store/accessories?tag=prototype' },
    ],
  },
  {
    group: 'Digital / Experimental / Prototype Projects',
    items: [
      { title: 'Experimental Studies', href: '#/store/archive?tag=prototype' },
      { title: 'Archive Objects', href: '#/store/archive?tag=archive' },
    ],
  },
];
