export const storeCategories = [
  {
    id: 'jewelry',
    title: 'Jewelry',
    deck: 'Small body extensions, talismans, metal and skin studies.',
    visualTone: 'bone',
  },
  {
    id: 'bags',
    title: 'Bags',
    deck: 'Body-carried forms, hardware, modular containers.',
    visualTone: 'steel',
  },
  {
    id: 'home-decor',
    title: 'Home Decor',
    deck: 'Interior objects, vessels, surfaces and sculptural fragments.',
    visualTone: 'void',
  },
  {
    id: 'clothes',
    title: 'Clothes',
    deck: 'Garments, layered silhouettes, soft armor and wearable studies.',
    visualTone: 'skin',
  },
];

export const storeProducts = [
  {
    id: 'spine-ring',
    name: 'Spine Ring',
    category: 'jewelry',
    price: 340,
    currency: 'USD',
    available: true,
    featured: 1,
    bestSelling: 3,
    date: '2026-03-18',
    tags: ['2026', 'silver'],
    visualTone: 'steel',
  },
  {
    id: 'bone-chain',
    name: 'Bone Chain',
    category: 'jewelry',
    price: 620,
    currency: 'USD',
    available: true,
    featured: 2,
    bestSelling: 2,
    date: '2025-12-02',
    tags: ['2025', 'bone'],
    visualTone: 'bone',
  },
  {
    id: 'skin-ear-piece',
    name: 'Skin Ear Piece',
    category: 'jewelry',
    price: 280,
    currency: 'USD',
    available: false,
    featured: 7,
    bestSelling: 7,
    date: '2024-10-09',
    tags: ['2024', 'skin'],
    visualTone: 'skin',
  },
  {
    id: 'skin-carrier',
    name: 'Skin Carrier',
    category: 'bags',
    price: 1180,
    currency: 'USD',
    available: true,
    featured: 1,
    bestSelling: 2,
    date: '2026-03-03',
    tags: ['2026', 'skin'],
    visualTone: 'skin',
  },
  {
    id: 'hardware-sling',
    name: 'Hardware Sling',
    category: 'bags',
    price: 980,
    currency: 'USD',
    available: true,
    featured: 3,
    bestSelling: 1,
    date: '2025-09-14',
    tags: ['2025', 'black', 'silver'],
    visualTone: 'black-steel',
  },
  {
    id: 'soft-case-object',
    name: 'Soft Case Object',
    category: 'bags',
    price: 640,
    currency: 'USD',
    available: false,
    featured: 6,
    bestSelling: 8,
    date: '2024-04-21',
    tags: ['2024', 'black'],
    visualTone: 'void',
  },
  {
    id: 'bone-vessel',
    name: 'Bone Vessel',
    category: 'home-decor',
    price: 820,
    currency: 'USD',
    available: true,
    featured: 1,
    bestSelling: 4,
    date: '2026-01-19',
    tags: ['2026', 'bone'],
    visualTone: 'bone',
  },
  {
    id: 'black-surface-study',
    name: 'Black Surface Study',
    category: 'home-decor',
    price: 540,
    currency: 'USD',
    available: true,
    featured: 3,
    bestSelling: 6,
    date: '2025-06-12',
    tags: ['2025', 'black'],
    visualTone: 'ink',
  },
  {
    id: 'silver-room-fragment',
    name: 'Silver Room Fragment',
    category: 'home-decor',
    price: 760,
    currency: 'USD',
    available: false,
    featured: 5,
    bestSelling: 7,
    date: '2024-11-07',
    tags: ['2024', 'silver'],
    visualTone: 'steel',
  },
  {
    id: 'skin-layer-top',
    name: 'Skin Layer Top',
    category: 'clothes',
    price: 690,
    currency: 'USD',
    available: true,
    featured: 1,
    bestSelling: 1,
    date: '2026-02-24',
    tags: ['2026', 'skin'],
    visualTone: 'skin',
  },
  {
    id: 'black-wrap-coat',
    name: 'Black Wrap Coat',
    category: 'clothes',
    price: 1420,
    currency: 'USD',
    available: true,
    featured: 2,
    bestSelling: 5,
    date: '2025-07-30',
    tags: ['2025', 'black'],
    visualTone: 'ink',
  },
  {
    id: 'bone-garment-study',
    name: 'Bone Garment Study',
    category: 'clothes',
    price: 880,
    currency: 'USD',
    available: false,
    featured: 8,
    bestSelling: 6,
    date: '2024-12-19',
    tags: ['2024', 'bone'],
    visualTone: 'bone',
  },
];
